# Form implementation generated from reading ui file 'view/add_wind_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(409, 557)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(70, 210, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 260, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 320, 55, 16))
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(130, 80, 161, 331))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.name_l = QtWidgets.QLineEdit(parent=self.widget)
        self.name_l.setObjectName("name_l")
        self.gridLayout.addWidget(self.name_l, 0, 0, 1, 1)
        self.desc_l = QtWidgets.QLineEdit(parent=self.widget)
        self.desc_l.setObjectName("desc_l")
        self.gridLayout.addWidget(self.desc_l, 1, 0, 1, 1)
        self.price_box = QtWidgets.QSpinBox(parent=self.widget)
        self.price_box.setObjectName("price_box")
        self.gridLayout.addWidget(self.price_box, 2, 0, 1, 1)
        self.disc_box = QtWidgets.QSpinBox(parent=self.widget)
        self.disc_box.setObjectName("disc_box")
        self.gridLayout.addWidget(self.disc_box, 3, 0, 1, 1)
        self.type_cb = QtWidgets.QComboBox(parent=self.widget)
        self.type_cb.setObjectName("type_cb")
        self.gridLayout.addWidget(self.type_cb, 4, 0, 1, 1)
        self.photo_l = QtWidgets.QLineEdit(parent=self.widget)
        self.photo_l.setObjectName("photo_l")
        self.gridLayout.addWidget(self.photo_l, 5, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(parent=Dialog)
        self.widget1.setGeometry(QtCore.QRect(90, 440, 261, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.cancel_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Цена"))
        self.label_2.setText(_translate("Dialog", "Скидка"))
        self.label_3.setText(_translate("Dialog", "Тип"))
        self.name_l.setPlaceholderText(_translate("Dialog", "Название"))
        self.desc_l.setPlaceholderText(_translate("Dialog", "Описание"))
        self.photo_l.setPlaceholderText(_translate("Dialog", "Фото 1.jpg"))
        self.save_btn.setText(_translate("Dialog", "Сохрнаить"))
        self.cancel_btn.setText(_translate("Dialog", "Отменить"))
