# Form implementation generated from reading ui file 'view/auth_wind_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(444, 489)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(140, 370, 171, 65))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.enter_btn = QtWidgets.QPushButton(parent=self.widget)
        self.enter_btn.setObjectName("enter_btn")
        self.gridLayout.addWidget(self.enter_btn, 0, 0, 1, 1)
        self.guest_btn = QtWidgets.QPushButton(parent=self.widget)
        self.guest_btn.setObjectName("guest_btn")
        self.gridLayout.addWidget(self.guest_btn, 1, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(parent=Form)
        self.widget1.setGeometry(QtCore.QRect(100, 180, 251, 91))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.login_l = QtWidgets.QLineEdit(parent=self.widget1)
        self.login_l.setObjectName("login_l")
        self.gridLayout_2.addWidget(self.login_l, 0, 0, 1, 1)
        self.password_l = QtWidgets.QLineEdit(parent=self.widget1)
        self.password_l.setObjectName("password_l")
        self.gridLayout_2.addWidget(self.password_l, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Авторизация"))
        self.enter_btn.setText(_translate("Form", "Войти"))
        self.guest_btn.setText(_translate("Form", "Войти как гость"))
        self.login_l.setPlaceholderText(_translate("Form", "Логин"))
        self.password_l.setPlaceholderText(_translate("Form", "Пароль"))
