# Form implementation generated from reading ui file 'view/product_wind_ui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(814, 600)
        Form.setMinimumSize(QtCore.QSize(700, 600))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 790, 516))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exit_btn = QtWidgets.QPushButton(parent=Form)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.search_l = QtWidgets.QLineEdit(parent=Form)
        self.search_l.setObjectName("search_l")
        self.horizontalLayout.addWidget(self.search_l)
        self.filt_cb = QtWidgets.QComboBox(parent=Form)
        self.filt_cb.setObjectName("filt_cb")
        self.horizontalLayout.addWidget(self.filt_cb)
        self.sort_cb = QtWidgets.QComboBox(parent=Form)
        self.sort_cb.setObjectName("sort_cb")
        self.horizontalLayout.addWidget(self.sort_cb)
        self.add_btn = QtWidgets.QPushButton(parent=Form)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.name_l = QtWidgets.QLabel(parent=Form)
        self.name_l.setText("")
        self.name_l.setObjectName("name_l")
        self.gridLayout.addWidget(self.name_l, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exit_btn.setText(_translate("Form", "Выйти"))
        self.add_btn.setText(_translate("Form", "Добавить"))
